		
    SELECT	GETDATE() 
	 SELECT DAY(ORDERDATE) FROM ORDERS
	  SELECT MONTH(ORDERDATE) FROM ORDERS
	   SELECT YEAR(ORDERDATE) FROM ORDERS
		 SELECT DATENAME(DW,ORDERDATE) FROM ORDERS --DATENAME( datepart , date )  
		   SELECT DATENAME(DW,ORDERDATE) FROM ORDERS
		    SELECT DATEPART(DW,ORDERDATE) FROM ORDERS
			     SELECT DATEADD(Day,1,OrderDate) FROM ORDERS
				 			     SELECT OrderDate FROM ORDERS
select * from orders
     SELECT orderdate,shippeddate,
		DATEDIFF(day,orderdate,shippeddate)
		FROM ORDERS
