SELECT TOP 2 FLOOR ( ORDERS.Freight ) FROM Orders ; SELECT TOP 2 Freight FROM ORDERS

SELECT TOP 2 CEILING ( ORDERS.Freight ) FROM Orders ;SELECT TOP 2 Freight FROM ORDERS

SELECT TOP 2 ROUND ( ORDERS.Freight,2 ) FROM Orders  ;SELECT TOP 2 Freight FROM ORDERS
SELECT  ROUND ( ORDERS.Freight,1 ) FROM Orders  ;SELECT  Freight FROM ORDERS
SELECT TOP 2 ROUND ( ORDERS.Freight,0 ) FROM Orders  ;SELECT TOP 2 Freight FROM ORDERS


SELECT TOP 2 POWER( ORDERS.Freight ,2 ) FROM Orders ;SELECT TOP 2 Freight FROM ORDERS

SELECT TOP 2 SQRT ( ORDERS.Freight ) FROM Orders SELECT TOP 2 Freight FROM ORDERS

SELECT TOP 2 ABS ( -2 ) FROM Orders