


         SELECT SUM(FREIGHT) FROM ORDERS

		 SELECT * FROM ORDERS

		SELECT SHIPCITY,SUM(FREIGHT) SUM_FREIGHT FROM ORDERS
		GROUP BY SHIPCITY
		ORDER BY SUM(FREIGHT) DESC

		-- NOT WORKING
	
			SELECT SHIPCITY,SUM(FREIGHT) SUM_FREIGHT FROM ORDERS
		GROUP BY SHIPCITY
		ORDER BY SUM(FREIGHT) SUM_FREIGHT DESC

		;
		--1 
		SELECT SHIPCITY,SUM(FREIGHT) FROM ORDERS
		GROUP BY SHIPCITY

		SELECT   SUM(FREIGHT) FROM ORDERS
		GROUP BY SHIPCITY
	
		SELECT O.OrderDate,SHIPCITY,  SUM(FREIGHT) FROM ORDERS O
		GROUP BY O.OrderDate , SHIPCITY

		SELECT SHIPCITY,  SUM(FREIGHT) FROM ORDERS O
		GROUP BY O.OrderDate
		--3 NOT WORKING
		SELECT SHIPCITY,  SUM(FREIGHT) FROM ORDERS O
		--4
		 --NOT WORKING
			SELECT  SHIPCITY ,ShipCountry, SUM(FREIGHT) FROM ORDERS
		    GROUP BY SHIPCITY

			--WORKING

			SELECT  SHIPCITY , SUM(FREIGHT) FROM ORDERS
		    GROUP BY SHIPCITY,SHIPCOUNTRY
		
		    SELECT  SHIPCITY , SUM(FREIGHT) FROM ORDERS
		    GROUP BY SHIPCITY

			SELECT  SHIPCITY ,SHIPCOUNTRY,SUM(FREIGHT) FROM ORDERS
		    GROUP BY SHIPCITY,SHIPCOUNTRY

		
	





	

SELECT * FROM ORDERS